%% Create Simulink Model with RL Agent for Missile Autopilot
% This script creates the Hinf_PID_RL.slx model programmatically
% Run this once to generate the model, then use train_rl_agent.m
% Author: Anirudha Talmale

clear; clc; close all;

%% Load original model structure
load('Data.mat');

%% Model name
mdl = 'Hinf_PID_RL';

% Check if model exists and close it
if bdIsLoaded(mdl)
    close_system(mdl, 0);
end

% Create new model
new_system(mdl);
open_system(mdl);

%% Set model configuration
set_param(mdl, 'Solver', 'ode45');
set_param(mdl, 'StopTime', '12');
set_param(mdl, 'FixedStep', '0.01');

%% Add blocks - Reference Signal
add_block('simulink/Sources/Repeating Sequence Stair', [mdl '/Reference'], ...
    'Position', [50, 200, 80, 230], ...
    'OutValues', '[50 -40 -15 15 -1 40]', ...
    'tsamp', '2');

%% Add Sum blocks for error calculation
add_block('simulink/Math Operations/Sum', [mdl '/Sum_Error'], ...
    'Position', [150, 200, 170, 220], ...
    'Inputs', '+-');

%% Add Derivative block for error derivative
add_block('simulink/Continuous/Derivative', [mdl '/Error_Derivative'], ...
    'Position', [200, 270, 230, 300]);

%% Add RL Agent block
add_block('rl_lib/RL Agent', [mdl '/RL Agent'], ...
    'Position', [300, 180, 400, 260]);

%% Add H-infinity controller path (Loop_nz -> Loop_alpha -> Loop_q)
add_block('simulink/Math Operations/Sum', [mdl '/Sum1'], ...
    'Position', [480, 200, 500, 220], ...
    'Inputs', '+-');

add_block('simulink/Continuous/Transfer Fcn', [mdl '/Loop_nz'], ...
    'Position', [530, 190, 615, 230], ...
    'Numerator', 'num_nz', ...
    'Denominator', 'dem_nz');

add_block('simulink/Math Operations/Sum', [mdl '/Sum2'], ...
    'Position', [650, 200, 670, 220], ...
    'Inputs', '+-');

add_block('simulink/Continuous/Transfer Fcn', [mdl '/Loop_alpha'], ...
    'Position', [700, 190, 785, 230], ...
    'Numerator', 'num_alpha', ...
    'Denominator', 'dem_alpha');

add_block('simulink/Math Operations/Sum', [mdl '/Sum3'], ...
    'Position', [820, 200, 840, 220], ...
    'Inputs', '+-');

add_block('simulink/Continuous/Transfer Fcn', [mdl '/Loop_q'], ...
    'Position', [870, 190, 955, 230], ...
    'Numerator', 'num_q', ...
    'Denominator', 'dem_q');

%% Add PID Controller
add_block('simulink/Continuous/PID Controller', [mdl '/PID'], ...
    'Position', [300, 350, 360, 390], ...
    'P', 'Kp', ...
    'I', 'Ki', ...
    'D', 'Kd', ...
    'N', '100');

%% Add Controller Blending block (MATLAB Function)
add_block('simulink/User-Defined Functions/MATLAB Function', [mdl '/Blend_Controllers'], ...
    'Position', [450, 280, 550, 340]);

% Set the MATLAB Function code
blend_func = sprintf(['function u = blend(k, hinf, pid)\n' ...
    '%% Blend H-infinity and PID outputs based on RL weighting factor k\n' ...
    '%% u = hinf*k + pid*(1-k)\n' ...
    'u = hinf*k + pid*(1-k);\n' ...
    'end']);

% Note: The MATLAB Function block code needs to be set manually in Simulink
% or through the Stateflow API. For now, we'll add a Fcn block instead.

% Remove the MATLAB Function and use a simpler approach
delete_block([mdl '/Blend_Controllers']);

% Use Product and Sum blocks for blending
add_block('simulink/Math Operations/Product', [mdl '/Prod_Hinf'], ...
    'Position', [450, 280, 480, 310], ...
    'Inputs', '**');

add_block('simulink/Math Operations/Sum', [mdl '/One_minus_k'], ...
    'Position', [420, 350, 440, 370], ...
    'Inputs', '+-');

add_block('simulink/Sources/Constant', [mdl '/One'], ...
    'Position', [380, 340, 400, 360], ...
    'Value', '1');

add_block('simulink/Math Operations/Product', [mdl '/Prod_PID'], ...
    'Position', [450, 380, 480, 410], ...
    'Inputs', '**');

add_block('simulink/Math Operations/Sum', [mdl '/Blend_Sum'], ...
    'Position', [520, 320, 540, 360], ...
    'Inputs', '++');

%% Add Actuator
add_block('simulink/Continuous/Transfer Fcn', [mdl '/Actuator'], ...
    'Position', [1000, 190, 1085, 230], ...
    'Numerator', '32400', ...
    'Denominator', '[1 254.5 32400]');

%% Add Saturation
add_block('simulink/Discontinuities/Saturation', [mdl '/Saturation'], ...
    'Position', [1120, 195, 1150, 225], ...
    'UpperLimit', '30', ...
    'LowerLimit', '-30');

%% Add Missile Dynamics (Nonlinear - as MATLAB Function)
add_block('simulink/User-Defined Functions/Interpreted MATLAB Function', [mdl '/Missile_Dynamics'], ...
    'Position', [1200, 170, 1320, 250], ...
    'MATLABFcn', 'missile_dynamics');

%% Add Scopes
add_block('simulink/Sinks/Scope', [mdl '/nz_Scope'], ...
    'Position', [1400, 90, 1430, 120]);

add_block('simulink/Sinks/Scope', [mdl '/Alpha_Scope'], ...
    'Position', [1400, 150, 1430, 180]);

add_block('simulink/Sinks/Scope', [mdl '/k_Scope'], ...
    'Position', [1400, 210, 1430, 240]);

%% Add Mux for observations (for RL Agent)
add_block('simulink/Signal Routing/Mux', [mdl '/Obs_Mux'], ...
    'Position', [250, 195, 255, 255], ...
    'Inputs', '3');

%% Add Reward Calculation
add_block('simulink/User-Defined Functions/Interpreted MATLAB Function', [mdl '/Reward_Calc'], ...
    'Position', [350, 450, 450, 490], ...
    'MATLABFcn', 'calc_reward');

%% Add ToWorkspace blocks
add_block('simulink/Sinks/To Workspace', [mdl '/nz_ToWS'], ...
    'Position', [1400, 270, 1460, 290], ...
    'VariableName', 'nz_data', ...
    'SaveFormat', 'Structure With Time');

%% Add connections (basic structure - you'll need to complete in Simulink)
% Reference -> Sum_Error
add_line(mdl, 'Reference/1', 'Sum_Error/1');

% Sum_Error -> Obs_Mux (error)
add_line(mdl, 'Sum_Error/1', 'Obs_Mux/1');

% Sum_Error -> Error_Derivative
add_line(mdl, 'Sum_Error/1', 'Error_Derivative/1');

% Error_Derivative -> Obs_Mux
add_line(mdl, 'Error_Derivative/1', 'Obs_Mux/2');

% Obs_Mux -> RL Agent
add_line(mdl, 'Obs_Mux/1', 'RL Agent/1');

%% Save model
save_system(mdl);
disp(['Model ' mdl '.slx created successfully!']);
disp('Please open the model and complete the remaining connections.');
disp('Key connections needed:');
disp('1. RL Agent output (k) -> Blending logic');
disp('2. H-inf controller chain -> Prod_Hinf');
disp('3. PID controller -> Prod_PID');
disp('4. Blended output -> Actuator -> Saturation -> Missile');
disp('5. Missile nz output -> feedback to Sum_Error and Obs_Mux');
disp('6. Reward calculation block connections');
